name: marcs-chip-ms-h3k4me1-h3k4me3
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - jupyterlab=3.3.0
    - numpy=1.22.2
    - pandas=1.4.0
    - pip=22.0.3
    - scipy=1.8.0
    - seaborn=0.11.2
    - tqdm=4.62.3
    - scikit-learn=1.0.2
    - missingno=0.4.2
    - matplotlib=3.5.1
    - matplotlib-venn=0.11.6
    - statsmodels=0.13.2
    - pandas-profiling=3.1.0
    - pingouin=0.5.1
    - xlsxwriter=3.0.2
    - xlrd=2.0.1
    - openpyxl=3.0.9
    - ipywidgets=7.6.5
    - adjusttext=0.7.3.1
    - patsy=0.5.2
    - r-base=4.1.2
    - r-dplyr=1.0.7
    - r-feather=0.3.5
    - r-ggplot2=3.3.5
    - r-ggrepel=0.9.1
    - r-gridextra=2.3
    - r-irkernel=1.3
    - r-lazyeval=0.2.2
    - r-readr=2.1.2
    - r-repr=1.1.4
    - r-markdown=1.1
    - r-tibble=3.1.6
    - r-tidyr=1.2.0
    - r-xml2=1.3.3
    - r-statmod=1.4.36
    - rpy2=3.4.5
    - bioconductor-biobase=2.54.0
    - bioconductor-complexheatmap=2.10.0
    - bioconductor-limma=3.50.1
    - feather-format=0.4.1
    - nb_conda_kernels=2.3.1
    - fancyimpute=0.7.0
    - pip
    - pip:
        - session-info
